name: Sitemap Workflow

on:
  workflow_run:
    workflows: ["Generate Workflow"]
    types:
      - completed
      
jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Find HTML Files
        id: find_html_files
        run: |
          # Find all HTML files in the repository, excluding 'index.html'
          html_files=$(find . -type f -name "*.html" ! -name "index.html" | sed 's|./||')
          echo "HTML_FILES=$html_files" >> $GITHUB_ENV

      - name: Generate Anchor Tags
        id: generate_tags
        run: |
          # Initialize the anchor tags variable
          anchor_tags=""

          # Loop through the HTML files to create anchor tags
          for file in $HTML_FILES; do
            file_name=$(basename $file)
            anchor_tags="$anchor_tags<a href=\"https://jokersl0t.github.io/joker/$file_name\"><p>$file_name</p></a>\n"
          done

          # Export the anchor tags as an environment variable for the next step
          echo "ANCHOR_TAGS=\"$anchor_tags\"" >> $GITHUB_ENV

      - name: Update index.html
        run: |
          # Read the current index.html
          index_file="index.html"
          
          # Separate the <head> and <body> contents
          head_content=$(sed -n '/<head>/,/<\/head>/p' $index_file)
          body_start=$(grep -n '<body>' $index_file | cut -d: -f1)
          body_end=$(grep -n '</body>' $index_file | cut -d: -f1)
          body_content=$(sed -n "$((body_start+1)),$((body_end-1))p" $index_file)
          
          # Inject the new anchor tags in the body
          new_body_content="<body>\n$ANCHOR_TAGS</body>"
          
          # Reconstruct the updated index.html
          echo -e "$head_content\n$new_body_content\n</html>" > $index_file

      - name: Commit and push changes
        run: |
            git config --global user.name "n00bc0d3r1"
            git config --global user.email "darktechdenny123@gmail.com"
            
            # Add the generated HTML files
            git add *.html
            
            # Check if there are any changes to commit
            if git diff --cached --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Generated HTML files from JSON"
              git push
            fi
        env:
            GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
