name: Create HTML Files from JSON

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate HTML files
        run: |
          # Create a directory to store the HTML files
          mkdir -p generated_html

          # Read JSON data
          json_data=$(cat news.json)
          account=$(echo "$json_data" | jq -r '.[0].account')
          repository=$(echo "$json_data" | jq -r '.[0].repository')
          
          # Loop through each item in the dynamic array and create an HTML file
          echo "$json_data" | jq -c '.[0].dynamic[]' | while read -r item; do
            filename=$(echo "$item" | jq -r '.filename')
            title=$(echo "$item" | jq -r '.title')
            meta_description=$(echo "$item" | jq -r '.meta-description')
            meta_source=$(echo "$item" | jq -r '.meta-source')
            image_logo=$(echo "$item" | jq -r '.image-logo')
            livechat_url=$(echo "$item" | jq -r '.livechat-url')

            # Use the template to create the HTML file
            sed -e "s/{{title}}/$title/g" \
                -e "s/{{meta-description}}/$meta_description/g" \
                -e "s/{{account}}/$account/g" \
                -e "s/{{repository}}/$repository/g" \
                -e "s/{{filename}}/$filename/g" \
                -e "s/{{meta-source}}/$meta_source/g" \
                -e "s|{{image-logo}}|$image_logo|g" \
                -e "s|{{livechat-url}}|$livechat_url|g" \
                template.html > "generated_html/$filename"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "n00bc0d3r1"
          git config --global user.email "darktechdenny123@gmail.com"
          git add generated_html/*
          git commit -m "Generated HTML files from JSON"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
